name: C Static Analysis

# Controls when the workflow will run
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  cppcheck:
    name: Run Cppcheck 🔬
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck

      - name: Create compilation database
        run: cmake -B build -S . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run Cppcheck Analysis
        run: >
          cppcheck
          --project=build/compile_commands.json
          --enable=all
          --inconclusive
          --suppress=missingIncludeSystem
          --xml
          --error-exitcode=1
          -i build
          2> cppcheck-report.xml

      - name: Generate HTML report
        run: cppcheck-htmlreport --file=cppcheck-report.xml --report-dir=cppcheck-html --source-dir=.
      
      - name: Upload Cppcheck HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cppcheck-html-report
          path: cppcheck-html

  deploy-pages:
    name: Deploy to GitHub Pages 🚀
    # This job requires the cppcheck job to succeed first
    needs: cppcheck
    # Only run this job on pushes to the main branch, not on pull requests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    # Grant permissions for the action to push to the gh-pages branch
    permissions:
      contents: write
      
    runs-on: ubuntu-latest
    steps:
      - name: Download HTML report artifact
        uses: actions/download-artifact@v4
        with:
          name: cppcheck-html-report
          path: ./report # Download the artifact into a 'report' directory

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The directory to publish from (where we downloaded the artifact)
          publish_dir: ./report
          # The directory to publish to on the gh-pages branch
          destination_dir: ./static-analysis
          # Cleans the destination directory before publishing
          keep_files: false

      - name: Show Deployed URL
        run: |
          # Extracts the repository name from the full 'owner/repo' string
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          echo "✅ View the deployed report at: https://${{ github.repository_owner }}.github.io/${REPO_NAME}/static-analysis/"