name: Unit Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build-and-test"
  build-and-test:
    name: Build and Test 🛠️
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configures the project using CMake
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}}

      # Builds the project, including the 'test_aes' executable
      - name: Build project
        run: cmake --build ${{github.workspace}}/build

      # Runs the tests defined in CMakeLists.txt
      - name: Run tests
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure